# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Requests::State.create(name: 'Aguascalientes')
Requests::State.create(name: 'Baja California')
Requests::State.create(name: 'Baja California Sur')
Requests::State.create(name: 'Campeche')
Requests::State.create(name: 'Chiapas')
Requests::State.create(name: 'Chihuahua')
Requests::State.create(name: 'Coahuila')
Requests::State.create(name: 'Colima')
Requests::State.create(name: 'Distrito Federal')
Requests::State.create(name: 'Durango')
Requests::State.create(name: 'Guanajuato')
Requests::State.create(name: 'Guerrero')
Requests::State.create(name: 'Hidalgo')
Requests::State.create(name: 'Jalisco')
Requests::State.create(name: 'México')
Requests::State.create(name: 'Michoacán')
Requests::State.create(name: 'Morelos')
Requests::State.create(name: 'Nayarit')
Requests::State.create(name: 'Nuevo León')
Requests::State.create(name: 'Oaxaca')
Requests::State.create(name: 'Puebla')
Requests::State.create(name: 'Querétaro')
Requests::State.create(name: 'Quintana Roo')
Requests::State.create(name: 'San Luis Potosí')
Requests::State.create(name: 'Sinaloa')
Requests::State.create(name: 'Sonora')
Requests::State.create(name: 'Tabasco')
Requests::State.create(name: 'Tamaulipas')
Requests::State.create(name: 'Tlaxcala')
Requests::State.create(name: 'Veracruz')
Requests::State.create(name: 'Yucatán')
Requests::State.create(name: 'Zacatecas')
Requests::State.create(name: 'Otro')
